version: '3.2'

services:
    sessions:
        image: redis:4
        ports: 
            - 6379:6379
        networks:
           web:
               aliases:
                   - redis

    cowsay-service:
        image: spsarolkar/cowsay 
        ports:
                - 8000
        environment:
            - SERVICE_PORTS=8000
        deploy:
            replicas: 5
            restart_policy:
                condition: on-failure
                max_attempts: 3
                window: 120s
        networks:
                web:
                   aliases:
                        - cowsay-cluster
 

    cowsay-proxy:
        image: dockercloud/haproxy:1.6.7
        depends_on:
            - cowsay-service
        environment: 
            - BALANCE=leastconn
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
                - "8000:80"
        networks:
            web:
               aliases:
                    - cowsay
        deploy:
            placement:
                constraints: [node.role == manager]

    cowsay-ui:
        image: spsarolkar/cowsay-ui
        ports:
                - "8080:8080"
        environment:
             - COWSAY_SERVER_NAME=cowsay
             - COWSAY_SERVER_PORT=80
             - REDIS_SERVER_NAME=redis
             - REDIS_SERVER_PORT=6379
        depends_on:
            - redis 
            - cowsay
        networks:
            web:

networks:
        web:
